# Generated by Django 5.0.1 on 2024-01-03 22:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "place_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sale_date", models.DateField()),
                ("eircode", models.CharField(max_length=7)),
                ("formatted_address", models.CharField(max_length=500)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Carlow", "Carlow"),
                            ("Cavan", "Cavan"),
                            ("Clare", "Clare"),
                            ("Cork", "Cork"),
                            ("Donegal", "Donegal"),
                            ("Dublin", "Dublin"),
                            ("Galway", "Galway"),
                            ("Kerry", "Kerry"),
                            ("Kildare", "Kildare"),
                            ("Kilkenny", "Kilkenny"),
                            ("Laois", "Laois"),
                            ("Leitrim", "Leitrim"),
                            ("Limerick", "Limerick"),
                            ("Longford", "Longford"),
                            ("Louth", "Louth"),
                            ("Mayo", "Mayo"),
                            ("Meath", "Meath"),
                            ("Monaghan", "Monaghan"),
                            ("Offaly", "Offaly"),
                            ("Roscommon", "Roscommon"),
                            ("Sligo", "Sligo"),
                            ("Tipperary", "Tipperary"),
                            ("Waterford", "Waterford"),
                            ("Westmeath", "Westmeath"),
                            ("Wexford", "Wexford"),
                            ("Wicklow", "Wicklow"),
                        ]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("is_full_market_price", models.BooleanField(default=True)),
                ("administrative_area_level_1", models.CharField(max_length=100)),
                ("administrative_area_level_2", models.CharField(max_length=100)),
                ("administrative_area_level_3", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                ("neighborhood", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=100)),
                ("route", models.CharField(max_length=100)),
                ("street_address", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=100)),
                ("sublocality", models.CharField(max_length=100)),
                ("stree_view_image_url", models.URLField()),
            ],
        ),
    ]
