# Generated by Django 5.0.1 on 2024-01-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0002_alter_property_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="administrative_area_level_1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="administrative_area_level_2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="administrative_area_level_3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="eircode",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="locality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="postal_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="route",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="stree_view_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="street_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="sublocality",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
