# Generated by Django 5.0.1 on 2024-01-04 22:28

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "place_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sale_date", models.DateField()),
                (
                    "raw_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "formatted_address",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Carlow", "Carlow"),
                            ("Cavan", "Cavan"),
                            ("Clare", "Clare"),
                            ("Cork", "Cork"),
                            ("Donegal", "Donegal"),
                            ("Dublin", "Dublin"),
                            ("Galway", "Galway"),
                            ("Kerry", "Kerry"),
                            ("Kildare", "Kildare"),
                            ("Kilkenny", "Kilkenny"),
                            ("Laois", "Laois"),
                            ("Leitrim", "Leitrim"),
                            ("Limerick", "Limerick"),
                            ("Longford", "Longford"),
                            ("Louth", "Louth"),
                            ("Mayo", "Mayo"),
                            ("Meath", "Meath"),
                            ("Monaghan", "Monaghan"),
                            ("Offaly", "Offaly"),
                            ("Roscommon", "Roscommon"),
                            ("Sligo", "Sligo"),
                            ("Tipperary", "Tipperary"),
                            ("Waterford", "Waterford"),
                            ("Westmeath", "Westmeath"),
                            ("Wexford", "Wexford"),
                            ("Wicklow", "Wicklow"),
                        ]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
                ),
                (
                    "lng",
                    models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sublocality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("premise", models.CharField(blank=True, max_length=100, null=True)),
                ("subpremise", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "postal_town",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("route", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stree_view_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("digest", models.CharField(max_length=32, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
