# Generated by Django 5.0.1 on 2024-01-09 09:09
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "county",
                    models.CharField(
                        choices=[
                            ("Carlow", "Carlow"),
                            ("Cavan", "Cavan"),
                            ("Clare", "Clare"),
                            ("Cork", "Cork"),
                            ("Donegal", "Donegal"),
                            ("Dublin", "Dublin"),
                            ("Galway", "Galway"),
                            ("Kerry", "Kerry"),
                            ("Kildare", "Kildare"),
                            ("Kilkenny", "Kilkenny"),
                            ("Laois", "Laois"),
                            ("Leitrim", "Leitrim"),
                            ("Limerick", "Limerick"),
                            ("Longford", "Longford"),
                            ("Louth", "Louth"),
                            ("Mayo", "Mayo"),
                            ("Meath", "Meath"),
                            ("Monaghan", "Monaghan"),
                            ("Offaly", "Offaly"),
                            ("Roscommon", "Roscommon"),
                            ("Sligo", "Sligo"),
                            ("Tipperary", "Tipperary"),
                            ("Waterford", "Waterford"),
                            ("Westmeath", "Westmeath"),
                            ("Wexford", "Wexford"),
                            ("Wicklow", "Wicklow"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=500, null=True)),
                ("digest", models.CharField(max_length=32, unique=True)),
                ("formatted_address", models.CharField(blank=True, max_length=500, null=True)),
                ("google_place_id", models.CharField(blank=True, max_length=500, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("neighborhood", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_town", models.CharField(blank=True, max_length=100, null=True)),
                ("premise", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("raw_address", models.CharField(blank=True, max_length=500, null=True)),
                ("route", models.CharField(blank=True, max_length=100, null=True)),
                ("sale_date", models.DateField()),
                ("sublocality", models.CharField(blank=True, max_length=100, null=True)),
                ("subpremise", models.CharField(blank=True, max_length=100, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
