# Generated by Django 5.0.1 on 2024-01-09 20:17
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="google_place_id",
        ),
        migrations.RemoveField(
            model_name="property",
            name="postal_town",
        ),
        migrations.RemoveField(
            model_name="property",
            name="premise",
        ),
        migrations.RemoveField(
            model_name="property",
            name="route",
        ),
        migrations.RemoveField(
            model_name="property",
            name="sublocality",
        ),
        migrations.RemoveField(
            model_name="property",
            name="subpremise",
        ),
        migrations.AddField(
            model_name="property",
            name="area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="house",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="location_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="street",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
