# Generated by Django 5.0.1 on 2024-01-11 09:14
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_alter_property_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=22, null=True),
        ),
    ]
